name: Bonifati.us
description: Catholic Web Apostolate
mission: Verbum dominum manet in aeternum
pygments: true
url: http://blog.bonifati.us

markdown: redcarpet
encoding: utf-8
permalink: /:year-:month-:day-:title

authors:
  johannes:
    name: Johannes Müller
  philipp:
    name: Philipp Müller