name: Bonifati.us
description: Catholic Web Apostolate
mission: Verbum dominum manet in aeternum
highligter: pygments
url: http://blog.bonifati.us

markdown: redcarpet
encoding: utf-8
permalinks: pretty
permalink: /:year-:month-:day-:title

authors:
  johannes:
    name: Johannes Müller
    mail: johannes@bonifati.us
  philipp:
    name: Philipp Müller
    mail: philipp@bonifati.us

prose:
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "subtitle"
        field:
          element: "text"
          label: "Subtitle"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Splash image"
          value: ""

# Build settings
exclude:
  - 'Rakefile'

# Server settings
port: 4000
host: 0.0.0.0

# settings for deployment (Rakefile)
git:
  repo: git@github.com:Bonifatius/bonifatius.github.io.git
  branch: master
